import queue, threading

grad=queue.Queue(2)
l_grad=queue.Queue(2)
r_grad=queue.Queue(2)
hes=queue.Queue(2)
l_hes=queue.Queue(2)
r_hes=queue.Queue(2)
results=queue.Queue(6)
lock1 = threading.Lock()
lock2 = threading.Lock()
lock3 = threading.Lock()
lock2.acquire()
lock3.acquire()
lock4 = threading.Lock()
lock5 = threading.Lock()
lock6 = threading.Lock()
lock5.acquire()
lock6.acquire()
